import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/navbar";

const soraSans = Sora({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${soraSans.variable} antialiased`}
      >
         <Navbar />
        {children}
      </body>
    </html>
  );
}
